export const requests = [
    {
        id: 1,
        requesterName: "Aman Moa",
        email: "aman@example.com",
        phoneNo: "091122334455",
        requestType: "hardware",
        description: "My PC stopped working all of a sudden",
        department: "HR",
        deviceType: "Laptop",
        modelNo: "SRC-25A",
        Urgency: "high",
        status: "Accepted"
      },
      {
        id: 2,
        requesterName: "Miki Alemu",
        email: "liya@example.com",
        phoneNo: "091122334456",
        requestType: "software",
        description: "Cannot install necessary software updates",
        department: "Finance",
        deviceType: "Desktop",
        modelNo: "XPS-13",
        Urgency: "medium",
        status: "Rejected"
      },
      {
        id: 3,
        requesterName: "Miki Alemu",
        email: "samuel@example.com",
        phoneNo: "091122334457",
        requestType: "network",
        description: "Wi-Fi connection keeps dropping",
        department: "IT",
        deviceType: "Router",
        modelNo: "NetGear-AC1200",
        Urgency: "high",
        status: "In Progress"
      },
      {
        id: 4,
        requesterName: "Miki Alemu",
        email: "betty@example.com",
        phoneNo: "091122334458",
        requestType: "hardware",
        description: "Printer is not working",
        department: "Admin",
        deviceType: "Printer",
        modelNo: "HP-LaserJet",
        Urgency: "low",
        status: "Completed"
      },
      {
        id: 5,
        requesterName: "Miki Alemu",
        email: "miki@example.com",
        phoneNo: "091122334459",
        requestType: "software",
        description: "Unable to access the accounting software",
        department: "Finance",
        deviceType: "Desktop",
        modelNo: "Dell-OptiPlex",
        Urgency: "medium",
        status: "Accepted"
      },
      {
        id: 6,
        requesterName: "Sara Mengistu",
        email: "sara@example.com",
        phoneNo: "091122334460",
        requestType: "network",
        description: "VPN connection issues",
        department: "IT",
        deviceType: "Router",
        modelNo: "Cisco-2000",
        Urgency: "high",
        status: "Completed"
      },
      {
        id: 7,
        requesterName: "John Doe",
        email: "john@example.com",
        phoneNo: "091122334461",
        requestType: "hardware",
        description: "Keyboard keys are stuck",
        department: "HR",
        deviceType: "Desktop",
        modelNo: "HP-Elite",
        Urgency: "low",
        status: "In Progress"
      },
      {
        id: 8,
        requesterName: "Helen Tadesse",
        email: "helen@example.com",
        phoneNo: "091122334462",
        requestType: "software",
        description: "Error message when opening Excel",
        department: "Admin",
        deviceType: "Laptop",
        modelNo: "Lenovo-ThinkPad",
        Urgency: "medium",
        status: "Rejected"
      },
      {
        id: 9,
        requesterName: "Daniel Gebremedhin",
        email: "daniel@example.com",
        phoneNo: "091122334463",
        requestType: "other",
        description: "Projector bulb needs replacement",
        department: "Marketing",
        deviceType: "Projector",
        modelNo: "Sony-X123",
        Urgency: "low",
        status: "In Progress"
      },
      {
        id: 10,
        requesterName: "Yared Tesfaye",
        email: "yared@example.com",
        phoneNo: "091122334464",
        requestType: "hardware",
        description: "Monitor screen is flickering",
        department: "IT",
        deviceType: "Monitor",
        modelNo: "Samsung-Curved",
        Urgency: "high",
        status: "Completed"
      },
      {
        id: 11,
        requesterName: "Martha Belete",
        email: "martha@example.com",
        phoneNo: "091122334465",
        requestType: "software",
        description: "Need help with antivirus installation",
        department: "Support",
        deviceType: "Desktop",
        modelNo: "Acer-Veriton",
        Urgency: "medium",
        status: "Rejected"
      },
      {
        id: 12,
        requesterName: "Michael Abebe",
        email: "michael@example.com",
        phoneNo: "091122334466",
        requestType: "network",
        description: "Internet is too slow",
        department: "Marketing",
        deviceType: "Router",
        modelNo: "NetGear-Nighthawk",
        Urgency: "high",
        status: "Rejected"
      },
      {
        id: 13,
        requesterName: "Selam Tesfaye",
        email: "selam@example.com",
        phoneNo: "091122334467",
        requestType: "hardware",
        description: "Mouse not responding",
        department: "IT",
        deviceType: "Mouse",
        modelNo: "Logitech-MX",
        Urgency: "low",
        status: "Accepted"
      },
      {
        id: 14,
        requesterName: "Abebe Tadesse",
        email: "abebe@example.com",
        phoneNo: "091122334468",
        requestType: "software",
        description: "Issue with database access",
        department: "HR",
        deviceType: "Desktop",
        modelNo: "HP-Pro",
        Urgency: "high",
        status: "In Progress"
      },
      {
        id: 15,
        requesterName: "Lena Solomon",
        email: "lena@example.com",
        phoneNo: "091122334469",
        requestType: "network",
        description: "Firewall issues",
        department: "IT",
        deviceType: "Firewall",
        modelNo: "Cisco-Firepower",
        Urgency: "medium",
        status: "Accepted "
      },
      {
        id: 16,
        requesterName: "Daniel Solomon",
        email: "daniel@example.com",
        phoneNo: "091122334470",
        requestType: "other",
        description: "Office temperature control",
        department: "Admin",
        deviceType: "Thermostat",
        modelNo: "Nest-Thermostat",
        Urgency: "low",
        status: "completed"
      },
      {
        id: 17,
        requesterName: "Hana Teklu",
        email: "hana@example.com",
        phoneNo: "091122334471",
        requestType: "hardware",
        description: "External hard drive not recognized",
        department: "Finance",
        deviceType: "Hard Drive",
        modelNo: "Seagate-Backup",
        Urgency: "high",
        status: "assigned"
      },
      {
        id: 18,
        requesterName: "Abel Getachew",
        email: "abel@example.com",
        phoneNo: "091122334472",
        requestType: "software",
        description: "Trouble with software license activation",
        department: "HR",
        deviceType: "Laptop",
        modelNo: "MacBook-Pro",
        Urgency: "medium",
        status: "doedLatter"
      },
      {
        id: 19,
        requesterName: "Tsedey Abraham",
        email: "tsedey@example.com",
        phoneNo: "091122334473",
        requestType: "network",
        description: "Network printer not accessible",
        department: "Support",
        deviceType: "Printer",
        modelNo: "Brother-HL",
        Urgency: "high",
        status: "completed"
      },
      {
        id: 20,
        requesterName: "Girma Tesfaye",
        email: "girma@example.com",
        phoneNo: "091122334474",
        requestType: "hardware",
        description: "Monitor not turning on",
        department: "IT",
        deviceType: "Monitor",
        modelNo: "LG-LED",
        Urgency: "high",
        status: "assigned"
      },



];

export const searchResults = [
  {
    id: 1,
    title: "How to Fix a Leaking Pipe",
    link: "https://example.com/fix-leaking-pipe",
    type: "Website",
    Description:
      "A leaking pipe can cause significant water damage. This guide provides step-by-step instructions on identifying the leak, turning off the water supply, and using a pipe patch kit or replacement pipe to fix the leak.",
  },
  {
    id: 2,
    title: "Repairing a Broken Window",
    link: "https://example.com/repair-window",
    type: "Website",
    Description:
      "A broken window can be a security risk and reduce your home's energy efficiency. This article explains how to remove broken glass safely, prepare the window frame, and install new glass or plexiglass.",
  },
  {
    id: 3,
    title: "How to Unclog a Drain",
    link: "https://example.com/unclog-drain",
    type: "Website",
    Description:
      "Clogged drains can be frustrating. This guide outlines methods to unclog drains using tools like a plunger, drain snake, or chemical drain cleaner, along with preventative tips.",
  },
  {
    id: 4,
    title: "Fixing a Leaking Roof",
    link: "https://www.youtube.com/watch?v=example",
    type: "Video",
    Description:
      "Roof leaks can lead to structural damage if not addressed promptly. This video tutorial shows how to locate the source of the leak, patch damaged shingles, and apply waterproof sealant to prevent further leaks.",
  },
];