export const requests = [
    {
      id: 1,
      UserName: "Aman Moa",
      email: "aman@gmail.com",
      password: "password123",
      status: "Activated",
      department: "HR",
      role:"Employee",
    },
    {
        id: 2,
        UserName: "Aman Moa",
        email: "aman@gmail.com",
        password: "password123",
        status: "Deactivated",
        department: "Dev",
        role:"Employee",
      },
      {
        id: 3,
        UserName: "Aman Moa",
        email: "aman@gmail.com",
        password: "password123",
        status: "Activated",
        department: "Machine Learning",
        role:"Employee",
      },
      {
        id: 4,
        UserName: "Aman Moa",
        email: "aman@gmail.com",
        password: "password123",
        status: "Activated",
        department: "Mentainace",
        role:"Employee",
      },
      {
        id: 5,
        UserName: "Aman Moa",
        email: "aman@gmail.com",
        password: "password123",
        status: "Activated",
        department: "Dev",
        role:"Employee",
      },
      {
        id: 6,
        UserName: "Aman Moa",
        email: "aman@gmail.com",
        password: "password123",
        status: "Activated",
        department: "HR",
        role:"Employee",
      },
      {
        id: 7,
        UserName: "Aman Moa",
        email: "aman@gmail.com",
        password: "password123",
        status: "Activated",
        department: "Dev",
        role:"Employee",
      },
      {
        id: 8,
        UserName: "Aman Moa",
        email: "aman@gmail.com",
        password: "password123",
        status: "Activated",
        department: "Dev",
        role:"Employee",
      },
      {
        id: 9,
        UserName: "Aman Moa",
        email: "aman@gmail.com",
        password: "password123",
        status: "Deactivated",
        department: "Machine Learning",
        role:"Employee",
      },
      {
        id: 10,
        UserName: "Aman Moa",
        email: "aman@gmail.com",
        password: "password123",
        status: "Activated",
        department: "Dev",
        role:"Employee",
      },
      {
        id: 11,
        UserName: "Aman Moa",
        email: "aman@gmail.com",
        password: "09-456-7890",
        status: "Activated",
        department: "Sales",
        role:"Employee",
      },
      {
        id: 12,
        UserName: "Aman Moa",
        email: "aman@gmail.com",
        password: "09-456-7890",
        status: "Activated",
        department: "Dev",
        role:"Employee",
      },
      {
        id: 13,
        UserName: "Aman Moa",
        email: "aman@gmail.com",
        password: "09-456-7890",
        status: "Activated",
        department: "Dev",
        role:"Employee",
      },
      {
        id: 14,
        UserName: "Aman Moa",
        email: "aman@gmail.com",
        password: "09-456-7890",
        status: "Activated",
        department: "Dev",
        role:"Employee",
      },
  ];